# .github/workflows/test.yml
name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.7.0  # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v2.3.1  # Use the latest version
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov-report html --cov=my_package tests/

      - name: Run main_script.py
        run: python main_script.py
