# .github/workflows/test.yml
name: Build

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - "*"
      
env:
  PROJECT_NAME: KommatiPara

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, "3.10"]
    
    
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 9
          submodules: false

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v1
        id: depcache
        with:
          path: deps
          key: requirements-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov-report html --cov=my_package tests/

      - name: Navigate to the script directory
        run: cd path/to/script

      - name: Run main_script.py
        run: python main_script.py
